version: '3'

services:
        mysql-development:
                image: mysql:8.0.17
                environment:
                        MYSQL_ROOT_PASSWORD: Password01
                        MYSQL_DATABASE: personal-data
                ports:
                        - "3308:3306"
        admin:
                image: adminer
                ports:
                        - "8090:8080"
